config/routes.rb
P::Application.routes.draw do
  get "admin/index"
	post 'slides/photo/:id' => 'slides#add_slide', as: :add_slide
  resources :photos do
		resources :comments, controller: 'photo_comment'
		member do
			post :like
		end
	end

	resources :categories, :products, :slides, :profiles

  captcha_route
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  root 'main#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :photos
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :img, PhotoUploader
	attr_accessor :uploader_secure_token
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	has_many :comments, class_name: "PhotoComment"
	has_and_belongs_to_many :categories

	mount_uploader :pic, PhotoUploader
	attr_accessor :uploader_secure_token
end

app/models/photo_comment.rb
class PhotoComment < ActiveRecord::Base
  belongs_to :user
	belongs_to :photo
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :images, dependent: :destroy
	belongs_to :user
	accepts_nested_attributes_for :images, allow_destroy: true

end

app/models/settings.rb
class Settings < Settingslogic
	source "#{Rails.root}/config/application.yml"
	namespace Rails.env
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :photo
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :photos
	has_many :products
	belongs_to :city
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
				 #:confirmable, :async
  validates :username, uniqueness: { case_sensitive: false }, length: {in: 5..20}

	mount_uploader :avatar, AvatarUploader
	attr_accessor :uploader_secure_token, :province

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

	def is_admin?
		admin
	end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(['username = :value OR lower(email) = lower(:value)', { value: login }]).first
    else
      where(conditions).first
    end
  end

	def update_with_password(params={})
		if !params[:current_password].blank? or !params[:password].blank? or !params[:password_confirmation].blank?
			super
		else
			params.delete(:current_password)
			self.update_without_password(params)
		end
	end

	def type_choiced?
		!user_type.nil?
	end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index

  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	respond_to :html, :json

	def index
		@photos = Photo.paginate(page: params[:page], per_page: 2)
		@slides = Slide.all

		respond_with(@photos, @slides)
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	respond_to :html, :json
	
	def index
		@photos = current_user.photos
		@products = current_user.products

		respond_with(@photos, @products)
	end

	def show
		@user = User.find(params[:id])

		@photos = @user.photos
		@products = @user.products
		
		respond_with(@user, @photos, @products)

	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def fulltitle(title)
    full_title = "云摄影"
    full_title += " | #{title}" unless title.blank?
    full_title
  end

	def show_user_type(user)
		if user.user_type == 1
			"爱秀"
		elsif user.user_type == 2
			"爱摄"
		else
			""
		end
  end

  def user_avatar_tag(user, options = {})
    options[:style] ||= :small
    style = case options[:style].to_s
              when "origin" then ""
              when "small" then "30x30"
              when "normal" then "190x190"
              when "large" then "240x240"
              when "large_w" then "960x"
              when "large_h" then "x960"
              else options[:style].to_s
            end
		if options[:image_options].nil?
			image_tag(user.avatar.url(style))
		else
			image_tag(user.avatar.url(style), options[:image_options])
		end
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    # for Bootstrap 3 pay attention to the classes in the "div"

    html = <<-HTML
  <div class="alert alert-warning alert-dismissable"> 
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h4>#{sentence}</h4>
  #{messages}</div>
    HTML
    html.html_safe
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/photo_comment_helper.rb
module PhotoCommentHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/profiles/index.html.erb
<div class="row profile">
	<div class="col-md-3">
		<div class="user_desc">
			<%= user_avatar_tag(current_user, style: :small, image_options: {class: 'img-rounded'}) %>
			<span><%= current_user.username %></span>
		</div>
	</div>
</div>
<hr />
<div class="row photos_wall">
	<div class="row"><%= link_to '添加照片', new_photo_path %></div>
    <% @photos.each_with_index do |photo, index| %>
			<% if index+1%4 == 0 %>
				<div class="row">
			<% end %>
			<div class="col-md-3 img-portfolio">
				<%=link_to image_tag( photo.pic.url(''), class: 'img-responsive img-hover img-rounded'), photo %>
        <%= link_to 'Show', photo %>
        <%= link_to 'Edit', edit_photo_path(photo) %>
        <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>
			<% if index+1%4 == 0 %>
				</div>
			<% end %>
    <% end %>
</div>
<hr />
<div class="row services_wall">
	<div class="row"><%= link_to '添加产品', new_product_path %></div>
    <% @products.each_with_index do |product, index| %>
			<% if index+1%4 == 0 %>
				<div class="row">
			<% end %>
			<div class="col-md-3 img-portfolio">
				<%=link_to image_tag( product.images.first.img.url(''), class: 'img-responsive img-hover img-rounded'), product %>
        <%= link_to 'Show', product %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>
			<% if index+1%4 == 0 %>
				</div>
			<% end %>
    <% end %>

</div>

app/views/profiles/show.html.erb
<div class="row profile">
	<div class="col-md-3">
		<div class="user_desc">
			<%= user_avatar_tag(@user, style: :small, image_options: {class: 'img-rounded'}) %>
			<span><%= @user.username %></span>
		</div>
	</div>
</div>
<h3>作品</h3>
<hr />
<div class="row wall">
    <% @photos.each_with_index do |photo, index| %>
			<div class="item" style="float:left;margin-left:10px">
				<%=link_to image_tag( photo.pic.url('190x190'), class: 'img-responsive img-hover img-rounded'), photo %>
			</div>
    <% end %>
</div>
<h3>服务</h3>
<hr />
<div class="row wall">
    <% @products.each_with_index do |product, index| %>
			<div class="item">
				<%=link_to image_tag(product.images.first.img.url('190x190'), class: 'img-responsive img-hover img-rounded'), product %>
			</div>
    <% end %>
</div>