config/routes.rb
P::Application.routes.draw do
  get "admin/index"
	post 'slides/photo/:id' => 'slides#add_slide', as: :add_slide
  resources :photos do
		resources :comments, controller: 'photo_comment'
		member do
			post :like
		end
	end

	resources :categories, :products, :slides, :profiles

  captcha_route
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  root 'main#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :photos
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :img, PhotoUploader
	attr_accessor :uploader_secure_token
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	has_many :comments, class_name: "PhotoComment"
	has_and_belongs_to_many :categories

	mount_uploader :pic, PhotoUploader
	attr_accessor :uploader_secure_token
end

app/models/photo_comment.rb
class PhotoComment < ActiveRecord::Base
  belongs_to :user
	belongs_to :photo
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :images, dependent: :destroy
	belongs_to :user
	accepts_nested_attributes_for :images, allow_destroy: true

end

app/models/settings.rb
class Settings < Settingslogic
	source "#{Rails.root}/config/application.yml"
	namespace Rails.env
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :photo
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :photos
	has_many :products
	belongs_to :city
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
				 #:confirmable, :async
  validates :username, uniqueness: { case_sensitive: false }, length: {in: 5..20}

	mount_uploader :avatar, AvatarUploader
	attr_accessor :uploader_secure_token, :province

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

	def is_admin?
		admin
	end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(['username = :value OR lower(email) = lower(:value)', { value: login }]).first
    else
      where(conditions).first
    end
  end

	def update_with_password(params={})
		if !params[:current_password].blank? or !params[:password].blank? or !params[:password_confirmation].blank?
			super
		else
			params.delete(:current_password)
			self.update_without_password(params)
		end
	end

	def type_choiced?
		!user_type.nil?
	end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index

  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	respond_to :html, :json

	def index
		@photos = Photo.paginate(page: params[:page], per_page: 2)
		@slides = Slide.all

		respond_with(@photos, @slides)
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	respond_to :html, :json
  before_action :set_photo, only: [:like, :show, :edit, :update, :destroy]

  def index
    @photos = Photo.paginate(page: params[:page], per_page: 1)
    respond_with(@photos)
  end

  def show
		@comments = @photo.comments.order("created_at DESC").paginate(page: params[:page], per_page: 3)
    respond_with(@photo, @comments)
  end

  def new
    @photo = Photo.new
    respond_with(@photo)
  end

  def edit
  end

  def create
    @photo = current_user.photos.build(photo_params)
    @photo.save
    respond_with(@photo)
  end

  def update
    @photo.update(photo_params)
    respond_with(@photo)
  end

  def destroy
    @photo.destroy
    respond_with(@photo)
  end

	def like
		Photo.increment_counter :praise, @photo.id
		@photo.reload
	end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:pic, :name, :description, :price, :location, :shoot_time, category_ids: [])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def fulltitle(title)
    full_title = "云摄影"
    full_title += " | #{title}" unless title.blank?
    full_title
  end

	def show_user_type(user)
		if user.user_type == 1
			"爱秀"
		elsif user.user_type == 2
			"爱摄"
		else
			""
		end
  end

  def user_avatar_tag(user, options = {})
    options[:style] ||= :small
    style = case options[:style].to_s
              when "origin" then ""
              when "small" then "30x30"
              when "normal" then "190x190"
              when "large" then "240x240"
              when "large_w" then "960x"
              when "large_h" then "x960"
              else options[:style].to_s
            end
		if options[:image_options].nil?
			image_tag(user.avatar.url(style))
		else
			image_tag(user.avatar.url(style), options[:image_options])
		end
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    # for Bootstrap 3 pay attention to the classes in the "div"

    html = <<-HTML
  <div class="alert alert-warning alert-dismissable"> 
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h4>#{sentence}</h4>
  #{messages}</div>
    HTML
    html.html_safe
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/photo_comment_helper.rb
module PhotoCommentHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/photos/_comment.html.erb
<li>
	comment: <%= comment.comment %>
	create_by: <%= comment.user.username %>
	create_at: <%= comment.created_at %>
</li>

app/views/photos/_form.html.erb
<%= simple_form_for(@photo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
		<% unless request.fullpath.include? 'edit'%>
    <%= f.input :pic, as: :file %>
		<% end %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :location %>
		<%= f.input :shoot_time, as: :string, input_html: {id: 'dt_shoot_time'}%>
		<%= f.association :categories, collection: Category.all, input_html: {class: 'chosen-select'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <thead>
    <tr>
      <th>Pic</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Location</th>
      <th>Shoot time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.pic %></td>
        <td><%= photo.name %></td>
        <td><%= photo.description %></td>
        <td><%= photo.price %></td>
        <td><%= photo.location %></td>
        <td><%= photo.shoot_time %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
	<%= will_paginate %>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/like.js.erb
<% if @photo.errors.empty? %>
	$('#like').html(<%= @photo.praise %>);
<% else %>
	alert('@photo.errors.full_messages.join(',')');
<% end %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pic:</strong>
  <%= @photo.pic %>
</p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @photo.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @photo.price %>
</p>

<p>
  <strong>Location:</strong>
  <%= @photo.location %>
</p>

<p>
  <strong>Shoot time:</strong>
  <%= @photo.shoot_time %>
</p>
<p>
  <strong>Categories:</strong>
	<% @photo.categories.each do |category| %>
  <%= category.name %>
	<% end %>
</p>
<p>
	<span id="like"><%= @photo.praise || 0 %></span>
	<%= link_to "like", like_photo_path(@photo), method: :post, remote: true %>
</p>
<p>
<%= simple_form_for PhotoComment.new, remote: true, url: photo_comments_path(@photo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</p>

<ul id="comments">
<%= render partial: 'comment', collection: @comments%>
</ul>

<%= will_paginate @comments %>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>