config/routes.rb
P::Application.routes.draw do
  get "admin/index"
	post 'slides/photo/:id' => 'slides#add_slide', as: :add_slide
  resources :photos do
		resources :comments, controller: 'photo_comment'
		member do
			post :like
		end
	end

	resources :categories, :products, :slides, :profiles

  captcha_route
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  root 'main#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :photos
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :img, PhotoUploader
	attr_accessor :uploader_secure_token
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	has_many :comments, class_name: "PhotoComment"
	has_and_belongs_to_many :categories

	mount_uploader :pic, PhotoUploader
	attr_accessor :uploader_secure_token
end

app/models/photo_comment.rb
class PhotoComment < ActiveRecord::Base
  belongs_to :user
	belongs_to :photo
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :images, dependent: :destroy
	belongs_to :user
	accepts_nested_attributes_for :images, allow_destroy: true

end

app/models/settings.rb
class Settings < Settingslogic
	source "#{Rails.root}/config/application.yml"
	namespace Rails.env
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :photo
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :photos
	has_many :products
	belongs_to :city
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
				 #:confirmable, :async
  validates :username, uniqueness: { case_sensitive: false }, length: {in: 5..20}

	mount_uploader :avatar, AvatarUploader
	attr_accessor :uploader_secure_token, :province

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

	def is_admin?
		admin
	end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(['username = :value OR lower(email) = lower(:value)', { value: login }]).first
    else
      where(conditions).first
    end
  end

	def update_with_password(params={})
		if !params[:current_password].blank? or !params[:password].blank? or !params[:password_confirmation].blank?
			super
		else
			params.delete(:current_password)
			self.update_without_password(params)
		end
	end

	def type_choiced?
		!user_type.nil?
	end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index

  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	respond_to :html, :json

	def index
		@photos = Photo.paginate(page: params[:page], per_page: 2)
		@slides = Slide.all

		respond_with(@photos, @slides)
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def fulltitle(title)
    full_title = "云摄影"
    full_title += " | #{title}" unless title.blank?
    full_title
  end

	def show_user_type(user)
		if user.user_type == 1
			"爱秀"
		elsif user.user_type == 2
			"爱摄"
		else
			""
		end
  end

  def user_avatar_tag(user, options = {})
    options[:style] ||= :small
    style = case options[:style].to_s
              when "origin" then ""
              when "small" then "30x30"
              when "normal" then "190x190"
              when "large" then "240x240"
              when "large_w" then "960x"
              when "large_h" then "x960"
              else options[:style].to_s
            end
		if options[:image_options].nil?
			image_tag(user.avatar.url(style))
		else
			image_tag(user.avatar.url(style), options[:image_options])
		end
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    # for Bootstrap 3 pay attention to the classes in the "div"

    html = <<-HTML
  <div class="alert alert-warning alert-dismissable"> 
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h4>#{sentence}</h4>
  #{messages}</div>
    HTML
    html.html_safe
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/layouts/_carousel.html.erb
<header id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
		<% @slides.each_with_index do |slide, index| %>
    <li data-target="#myCarousel" data-slide-to="<%= index %>" <% if index == 0 %>class="active"><% end %></li>
		<% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
		<% @slides.each_with_index do |slide, index| %>
    <div class="item<% if index == 0 %> active<% end %>">
			<a href="<%= photo_path(slide.photo) %>"><div class="fill" style="background-image:url('<%= slide.photo.pic.url('') %>');"></div></a>
      <div class="carousel-caption">
        <h2><%= link_to slide.photo.name, photo_path(slide.photo) %></h2>
      </div>
    </div>
		<% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</header>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p>Copyright &copy; Your Website 2014</p>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-static-top" role="navigation">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to raw('<img src="/assets/logo.jpg" class="logo" />'), root_path %>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li>
				<%= link_to raw('<span class="glyphicon glyphicon-home"></span> 首页'), root_path %>
				</li>
				<li>
				<%= link_to raw('<span class="glyphicon glyphicon-user"></span> 关于我们'), root_path %>
				</li>
				<li>
				<%= link_to raw('<span class="glyphicon glyphicon-envelope"></span> 联系我们'), root_path %>
				</li>
				<% if current_user %>
					<% if current_user.is_admin? %>
					<li>
					<%= link_to '后台管理', admin_index_path %>
					<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= user_avatar_tag(current_user, style: :small, image_options: {class: 'img-circle'}) %> <%=current_user.email %> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to '个人中心', profiles_url %></li>
							<li><%= link_to '资料设置', edit_user_registration_path%></li>
							<li><%= link_to '退出', destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
					</li>
					<% else %>
					<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= user_avatar_tag(current_user, style: :tiny, image_options: {class: 'img-rounded'}) %> <%=current_user.email %> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to '管理', profile_index_path %></li>
							<li><%= link_to '个人资料设置', edit_user_registration_path%></li>
							<li><%= link_to '退出', destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
					<% end %>
				<% else %>
					<li><%= link_to raw('<span class="glyphicon glyphicon-pencil"></span> 注册'), new_user_registration_path %></li>
					<li><%= link_to raw('<span class="glyphicon glyphicon-log-in"></span> 登录'), new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container -->
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= fulltitle(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>
</head>
<body>

<!-- Navigation -->
<%= render 'layouts/nav' %>

<!-- Page Content -->
<div class="container">
	<%= render 'shared/message' %>
	<div class="row">
		<div class="col-md-3">
			<ul class="nav nav-pills nav-stacked" role="tablist">
	 			<li role="presentation" class="active"><%= link_to 'Slide管理', slides_url %></li>
	   		<li role="presentation"><a href="#">Profile</a></li>
		   	<li role="presentation"><a href="#">Messages</a></li>
			</ul>
		</div>
		<div class="col-md-9">
	    <%= yield %>
		</div>
	</div>
	<hr>
	<!-- Footer -->
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</div>
<!-- /.container -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= fulltitle(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>
</head>
<body>

<!-- Navigation -->
<%= render 'layouts/nav' %>
<% if request.fullpath == '/' %>
<!-- Header Carousel -->
<%= render 'layouts/carousel' %>
<% end %>

<!-- Page Content -->
<div class="container">
	<%= render 'shared/message' %>
	<%= yield %>
	<hr>
	<!-- Footer -->
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</div>
<!-- /.container -->

<!-- Script to Activate the Carousel -->
<script>
$('.carousel').carousel({
interval: 5000 //changes the speed
})
</script>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_message.html.erb
	<% flash.each do |key,value| %>
	<div class="alert alert-<%= key %>">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<%= value %>
	</div>
	<% end %>